name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      csv_url: "MLproject/personality_preprocessing_datasert.csv"
      target_var: "Personality"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy joblib

      - name: Start MLflow Tracking Server
        run: |
          nohup mlflow server \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root ./mlruns \
            --host 127.0.0.1 \
            --port 5000 > mlflow.log 2>&1 &
          sleep 10
        shell: bash

      - name: Set MLflow Tracking URI
        run: echo "MLFLOW_TRACKING_URI=http://127.0.0.1:5000" >> $GITHUB_ENV

      - name: Run MLflow Project
        run: |
          mlflow run MLproject/ --env-manager=local

      - name: Get Latest MLflow run_id
        run: |
          RUN_ID=$(find mlruns/0 -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | grep -E '^[a-f0-9]{32}$' | head -n 1)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Build Docker Model Image
        run: |
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name personality_predict

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag and Push Docker Image
        run: |
          docker tag personality_predict ${{ secrets.DOCKER_HUB_USERNAME }}/personality_predict:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/personality_predict:latest
